---
- name: Read a Certificate from Vault
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"

  tasks:
   - name: 01 - Read The Certificate from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "{{ fqdn }}"
      auth_method: token
      token: "{{ ansible_password }}"
     register: cert_info


   - name: Get certificate information
     community.crypto.x509_certificate_info:
       content: "{{ cert_info.data.data.cert }}"
     register: cert_info


   - name: Timmay HARD STOP this Playbook
     ansible.builtin.meta: end_play
