---
- name: Get a List of the ISE Nodes v2.0
  hosts: localhost
  gather_facts: false
  tasks:

    - name: 01 - Get a List of the ISE Nodes
      cisco.ise.node_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: true
        ise_debug: true
      register: ise_deployment_info
      timeout: 120


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

